### ISSUE TITLE
Question: Polarity of Mod-T power supply

### ISSUE THREAD

**Issue by wizard23** [tripflex/MOD-t#3]
Hi, sorry to post this question here: Can anybody who owns a mod-t meaure the power supply and tell me if plus is on the inside or the outside of the connector? I lost the power supply and need to replace it but I dont want to fry it...

**Comment by rokhead** [comment]
inside is positive, outside is ground.
24v DC, 2.5A output

**Comment by wizard23** [comment]
kthnx!
