### ISSUE TITLE
I found the NewMatter User Manual 

### ISSUE THREAD

**Issue by ehernan3** [tripflex/MOD-t#7]
@tripflex , I've also uncovered the NewMatter User Manual. Since many web searches keep pointing me to your repo, I'm going to keep volunteering to add to it for 'one stop shopping'. Would you like me to add it to this repo, and if so, where?

**Comment by ehernan3** [comment]
[UserGuide](https://www.treatstock.com/static/uploads/printers/NewMatter_UserGuide.pdf)

**Comment by tripflex** [comment]
@ehernan3 awesome thanks i added it to the main repo area 👍
